export const styles = theme => {
  theme.breakpoints.values.sm = 480;
  theme.breakpoints.values.md = 768;
  theme.breakpoints.values.lg = 1024;
  return {
    container: {
      width: '90vw',
      // height: '70vh',
      display: 'flex',
      flexDirection: 'row',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    helperText: {
      width: '100%',
      textAlign: 'center',
      marginBottom: 10,
    },
    card: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },

      backgroundColor: '#337A89',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    secondCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#337A89',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '40%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    cardContainer: {
      [theme.breakpoints.between('xs', 'sm')]: {
        flexDirection: 'column',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 0,
        // height: '90%',
        minHeight: 650,
      },
      display: 'flex',
      alignItems: 'center',
      flexDirection: 'column',
      width: '50%',
      // height: '55%',
      // maxHeight: 325,
      marginBottom: 20,
    },
    chewsitCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#D36F75',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    chewsitText: {
      fontFamily: 'Oleo Script Swash Caps',
      color: '#ECEBE3',
      fontSize: '4rem',
    },
    chewsitFadeCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#ECEBE3',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    weightedRandomizerCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#3f51b5',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    weightedRandomizerFadeCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    weightedRandomizerText: {
      paddingLeft: 10,
      paddingRight: 10,
      color: '#ECEBE3',
      fontWeight: 'bold',
      fontSize: '2.5rem',
      marginLeft: 'auto',
      marginRight: 'auto',
      textAlign: 'center',
    },
    etapCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#60783A',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    etapFadeCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#60783A',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    etapText: {
      color: '#ECEBE3',
      fontWeight: 'bold',
      fontSize: '2.5rem',
      margin: 'auto',
      textAlign: 'center',
    },
    simpleServerFadeCard: {
      [theme.breakpoints.between('xs', 'sm')]: {
        width: '100%',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginBottom: 25,
      },
      backgroundColor: '#ffffff',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      maxWidth: 400,
      height: '40vh',
      maxHeight: 300,
      cursor: 'pointer',
    },
    none: {
      display: 'none',
    },
    infoDiv: {
      marginTop: 10,
      marginLeft: 20,
      paddingRight: 20,
    },
    innerCardContainer: {
      width: '85%',
      margin: 'auto',
      maxWidth: 390,
    },
    expandButton: {
      width: '100%',
    },
    ul: {
      width: '100%',
      display: 'inline-block',
      listStyleType: 'circle',
    },
    li: {
      marginRight: 30,
      marginBottom: 12,
      float: 'left',
    },
  };
};
